create table "public"."thing" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "name" text not null,
    "type" text not null
);

alter table "public"."thing" enable row level security;

create unique index thing_pkey ON public.thing USING btree (id);
-- Create an index on the filter column
create index thing_type_idx ON public.thing USING btree (type);

alter table "public"."thing" add constraint "thing_pkey" PRIMARY KEY using index "thing_pkey";

create policy "Enable read access for all users"
on "public"."thing"
as permissive
for select
to public
using (true);

drop publication if exists supabase_realtime;
create publication supabase_realtime;
alter publication supabase_realtime add table "thing";

create extension if not exists "moddatetime" with schema "extensions";
create trigger handle_updated_at before update on "thing"
  for each row execute procedure moddatetime (updated_at);
